# Generated by Django 4.1.6 on 2023-03-06 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='StatusTestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('estimate', models.CharField(max_length=255)),
                ('precondition', models.TextField(blank=True)),
                ('steps', models.TextField()),
                ('expected_result', models.TextField()),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.priority')),
            ],
        ),
        migrations.CreateModel(
            name='TestProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.projectstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('description', models.TextField(blank=True)),
                ('testProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.testproject')),
            ],
        ),
        migrations.CreateModel(
            name='TestRunTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testCase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.testcase')),
                ('testRun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.testrun')),
            ],
        ),
        migrations.CreateModel(
            name='TestSuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('description', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.testproject')),
            ],
        ),
        migrations.AddField(
            model_name='testrun',
            name='testcases',
            field=models.ManyToManyField(through='tms.TestRunTestCase', to='tms.testcase'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='testSuit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.testsuit'),
        ),
        migrations.CreateModel(
            name='TestRunResult',
            fields=[
                ('testrunTestcase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tms.testruntestcase')),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('trrDate', models.DateTimeField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tms.statustestrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
